### ISSUE TITLE
fork后运行一直失败

### ISSUE THREAD

**Issue by yimouleng** [tyIceStream/zodgame_checkin#1]
报错：
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
签到失败
Traceback (most recent call last):
  File "./zodgame/zodgame.py", line 64, in <module>
    zodgame(cookie_string)
  File "./zodgame/zodgame.py", line 58, in zodgame
    assert "恭喜你签到成功!" in message or "您今日已经签到，请明天再来" in message
AssertionError
Error: Process completed with exit code 1.

**Comment by tyIceStream** [comment]
大概率是因为没有正确输入Cookie导致的。
输入的Cookie可以采用手动复制或者复制值的方式。
不要携带前面的【Cookie:】字样

如果你本地有环境，可以自己去掉--headless的语句运行一下，如果页面是没有登陆的页面，那就是Cookie没对。

**Comment by yimouleng** [comment]
使用的是复制值的方式，也是登录后获取的Cookie， 也检查过是不是Cookie的问题，但是反复确认后发现Cookie没有问题

`qhMq_2132_saltkey=TlJX05mL; qhMq_2132_lastvisit=1636976315; qhMq_2132_auth=f8d9ZM8LHWhgHV6KAsIFW/vgHUIeTmnxUOjg/NG550DxFZPq33yRXWi70ekzdvIEgoN3OnUt+zJc47xVs9uM+lmPUag; qhMq_2132_lastcheckfeed=744643|1636979925; qhMq_2132_nofavfid=1; qhMq_2132_smile=4D1; qhMq_2132_myrepeat_rr=R0; qhMq_2132_forum_lastvisit=D_17_1636983839D_16_1637044340D_103_1637055644D_4_1637055646D_99_1637060252D_97_1637248060D_90_1637248257D_2_1637248666D_110_1637248911D_104_1637249181D_36_1637249318D_13_1637252833; qhMq_2132_sid=BcANX1; qhMq_2132_lip=111.218.68.123,1637260236; qhMq_2132_onlineusernum=479; qhMq_2132_ulastactivity=ebcbqBTjRnns/sN18YWqubWhL5U4y3FetClwxQfYW7BIT8DErU0x; qhMq_2132_checkpm=1; qhMq_2132_sendmail=1; qhMq_2132_lastact=1637304211	misc.php	patch`

**Comment by yimouleng** [comment]
另外发现 控制台使用手机模式后的Cookie  全屏模式 和 手机版 的不相同， 有些参数不一样，   是这个导致的吗？应该使用手机模式获取的 Cookie  ？

**Comment by tyIceStream** [comment]
我在本地测试了你的Cookie，是登陆不上去的。
如果你是11月份之前就注册过zodgame的，建议你退出登陆，然后重新登陆一下，重获取一遍Cookie。
然后在论坛里多点几个页面，再新的Cookie填进去。

没有测试过手机模式，就用PC模式就OK。

**Comment by yimouleng** [comment]
好的吧，我重新尝试下，但是我本地没有环境没法测试很麻烦

**Comment by tyIceStream** [comment]
或者你用无痕模式登陆一下，然后重获取Cookie。
记得在论坛里多点几个页面，然后导出Cookie。（不确定这样是否确实奏效，感觉多点几个页面之后Cookie会变多，没有做具体测试）

**Comment by yimouleng** [comment]
无痕模式，重新登录啥的都试了，依然失败了，人傻了。

**Comment by tyIceStream** [comment]
你的Cookie比我的少好几项呢，应该是没获取全。

我的操作步骤：
1.打开无痕模式
2.登陆进去
3.打开开发者工具-网络（此时没有任何记录）
4.刷新页面
5.从新的请求里获取到Cookie。

我这样操作是可行的，浏览器Chrome。

**Comment by yimouleng** [comment]
运行成功了，试了很多个Cookie，没用无痕模式，重新登录一次，但是多了home的一个参数，反正就是莫名其妙的复制过去就成功了

**Comment by yimouleng** [comment]
最新更新的去除了version_main=95，但是手动运行偶尔依然报错script timeout (Session info: chrome=97.0.4692.71)

手贱更换了Cookie，一直失败了
`Run python3 ./zodgame/zodgame.py "***"
  python3 ./zodgame/zodgame.py "***"
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.7.9\x64
签到失败
Traceback (most recent call last):
  File "./zodgame/zodgame.py", line 71, in <module>
    zodgame(cookie_string)
  File "./zodgame/zodgame.py", line 62, in zodgame
    assert "\u606d\u559c\u4f60\u7b7e\u5230\u6210\u529f!" in message or "\u60a8\u4eca\u65e5\u5df2\u7ecf\u7b7e\u5230\uff0c\u8bf7\u660e\u5929\u518d\u6765" in message
AssertionError
Error: Process completed with exit code 1.`

尝试了2小时，更换了20多次Cookie，还是不行。
Cookie如下：
`cf_clearance=hbB93XS2LCIDZmH6jhLZxx0EIPAh7X9s4wg5sOF7gsM-1642320945-0-150; qhMq_2132_saltkey=v8r3571d; qhMq_2132_lastvisit=1642317355; qhMq_2132_ulastactivity=1642320993|0; qhMq_2132_auth=b594lBCBYXPmqm4jzLs0famjdYshQoYlitYi0ZeyTeYWvC2qbGDsNmTcD60nq/FUATehXKfD4z2IxRa+luex6oUqm2M; qhMq_2132_lastcheckfeed=744643|1642320993; qhMq_2132_lip=162.158.179.249,1642320993; qhMq_2132_myrepeat_rr=R0; qhMq_2132_seccodecS=19826.b58343444355990ac4; qhMq_2132_sid=0; qhMq_2132_nofavfid=1; qhMq_2132_sendmail=1; qhMq_2132_lastact=1642321550	forum.php	viewthread; qhMq_2132_st_p=744643|1642321550|1f3ef5c1073196fdf86f59e6ac30b45b; qhMq_2132_viewid=tid_343260; qhMq_2132_smile=4D1`

**Comment by tyIceStream** [comment]
Timeout暂时不清楚，可能是因为那个时间点访问人太多导致的。
这个地方出现一堆\u字符串是因为action我换了windows的镜像来运行，好处是默认带图形界面，不用在headless下运行，兼容性会更强。

Cookie现在只需要qhMq_2132_saltkey和qhMq_2132_auth就好了，其他的没啥用，另外你可以尝试从浏览器的Cookie里直接把这两项取出来拼凑一下。（谷歌浏览器，开发者工具，Application，左边Cookies）。

**Comment by yimouleng** [comment]
好的，我重新尝试下，你每次回复都好快

**Comment by tyIceStream** [comment]
哈，有邮件推送的，我看到就回了。

**Comment by yimouleng** [comment]
废了我，三个多小时了，各种方式各种cookie都试了，还是失败，头疼

**Comment by tyIceStream** [comment]
我晚上试一下你的Cookie，或者你可以加一下我QQ，653297351

**Comment by yimouleng** [comment]
加Q了，麻烦了
