### ISSUE TITLE
又不能正常签到了

### ISSUE THREAD

**Issue by ketchup1995** [tyIceStream/zodgame_checkin#10]
![图片](https://user-images.githubusercontent.com/87350553/154872544-665cc696-e072-4966-905f-a573cdc7eaa1.png)

**Comment by tyIceStream** [comment]
Script timeout的问题是因为网络拥堵导致的，手动re-run一下就没问题了。你想彻底解决就先把签到时间往后调几个小时，8点多签到的人比较多。
