### ISSUE TITLE
有没有可能添加一个自动看广告的功能呢?

### ISSUE THREAD

**Issue by Ira125** [tyIceStream/zodgame_checkin#11]
zodgame的广告每天固定6积分,1积分换1酱油,是比签到更快更稳定的酱油来源.能不能添加一个每天自动看广告的功能?

**Comment by tyIceStream** [comment]
非常感谢你的提议，该功能的具体方案将在未来的更新中给出。

**Comment by Ira125** [comment]
好的,感谢您的工具,期待您未来的更新

**Comment by tyIceStream** [comment]
New feature has deployed. Pls have a try.
