### ISSUE TITLE
请问为什么带了Cookie，还是登录不上去

### ISSUE THREAD

**Issue by bpefei** [tyIceStream/zodgame_checkin#13]
报错信息：
![截屏2022-02-28 14 26 23](https://user-images.githubusercontent.com/46258823/155934929-1f8442c9-8146-4a7a-a62f-fb613aa98012.png)

我在本地调试了一下，发现在zodgame_checkin这个函数中获得的resp，是论坛的登录界面（输入用户名密码的），然后match是None

我试了很多次重新复制Cookie还是不行

**Comment by tyIceStream** [comment]
就是Cookie没对，Cookie对了就应该能登进去

**Comment by bpefei** [comment]
> 

谢谢，我之前一直是在Cookie那一项上右键“复制值”复制的，现在鼠标框选复制了一次就可以了
