### ISSUE TITLE
请问workflows是失效了吗 

### ISSUE THREAD

**Issue by skshuail** [tyIceStream/zodgame_checkin#18]
![image](https://user-images.githubusercontent.com/83758814/170849421-5c6487f7-d8a0-4618-b36b-5777cf771ba7.png)
不自行手动启用不会自动触发了？ 如何重新恢复每天自动启动

**Comment by tyIceStream** [comment]
Github action对于不活跃的仓库会自动停止的，这个问题在新版本已经解决了。
建议你对仓库进行一次push操作重新激活一下就可以了。

**Comment by skshuail** [comment]
> Github action对于不活跃的仓库会自动停止的，这个问题在新版本已经解决了。 建议你对仓库就进行一次操作重新激活一下可以了。
请问如何重新激活。已经两次手动激活run了，还是无法使他自动运行。

**Comment by tyIceStream** [comment]
你提交一个push就可以了，如果实在不熟悉github的操作，可以重新fork这个仓库
