### ISSUE TITLE
可以将checkout@v2改成v3以解决"Node.js 12 actions are deprecated."的warning

### ISSUE THREAD

**Issue by GrandDuke1106** [tyIceStream/zodgame_checkin#25]
可以将workflows的配置文件的第17行
```
- uses: actions/checkout@v2
```
改成
```
- uses: actions/checkout@v3
```

可以解决''Node.js 12 actions are deprecated.''的问题

>Annotations
1 warning
build
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by tyIceStream** [comment]
Thanks
