### ISSUE TITLE
跟著做結果出現code 1

### ISSUE THREAD

**Issue by g9772509** [tyIceStream/zodgame_checkin#28]
如提，我在做workflow的時候出現urllib.error.HTTPError: HTTP Error 404: Not Found
請問如何修正?

![image](https://github.com/tyIceStream/zodgame_checkin/assets/134082770/a43b0109-19c6-45ad-8c72-72c0ed09da4b)

**Comment by tyIceStream** [comment]
这个报错在初始化Chrome的时候就发生了，大概率是网络原因，可以考虑等待一段时间重试。

**Comment by tyIceStream** [comment]
该问题是由上游依赖库的问题导致，将由上游修复。
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1419

**Comment by g9772509** [comment]
謝啦~ 可以用了
