### ISSUE TITLE
自动运行会报错，手动才能签成功

### ISSUE THREAD

**Issue by angelas1qiaolezi** [tyIceStream/zodgame_checkin#6]
![$FC D89XKMNTRNT7MKFX841](https://user-images.githubusercontent.com/90556379/149689195-eb5adc3d-86d0-4b3d-b718-19679a431ebb.png)

**Comment by tyIceStream** [comment]
你贴图的这个是因为依赖库的更新导致的，如果失败了可以尝试向本仓库同步。本仓库会尽可能尽快解决bug。
有时也会发生自动签到出错手动又成功的情况，主要是由于签到时段网络异常导致的，如果不介意签到时间的可以考虑把签到时间往后推迟几个小时会好很多。
