### ISSUE TITLE
 前几天能正常自动签到，今天就不行了，报错如下图

### ISSUE THREAD

**Issue by ketchup1995** [tyIceStream/zodgame_checkin#7]
![图片](https://user-images.githubusercontent.com/87350553/152474776-f280aa37-82b9-4d53-b4e2-40181044a4ff.png)

**Comment by tyIceStream** [comment]
该问题已知晓，随后会推送更新。

**Comment by tyIceStream** [comment]
该问题已修复，请自行同步
